--
-- PostgreSQL database dump
--

\restrict NhRcb8A1qdsE1pwK5yqCE4kaUx1pWKFM7UJRDq1raEwz9EZNPX9Xo4dFJOrPCfJ

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-05-04 19:12:30

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 24800)
-- Name: admission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admission (
    student_id bigint NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    program character varying(255),
    year_level character varying(255),
    sex character varying(255),
    section character varying(255),
    department character varying(255),
    validated boolean,
    id bigint NOT NULL
);


ALTER TABLE public.admission OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 24932)
-- Name: admission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 24799)
-- Name: admission_student_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.admission_student_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.admission_student_id_seq OWNER TO postgres;

--
-- TOC entry 5048 (class 0 OID 0)
-- Dependencies: 219
-- Name: admission_student_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.admission_student_id_seq OWNED BY public.admission.student_id;


--
-- TOC entry 224 (class 1259 OID 24861)
-- Name: registration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registration (
    registration_id integer NOT NULL,
    student_id integer,
    student_schedule_id integer,
    status character varying(50),
    date_enrolled date
);


ALTER TABLE public.registration OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24860)
-- Name: registration_registration_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.registration_registration_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.registration_registration_id_seq OWNER TO postgres;

--
-- TOC entry 5049 (class 0 OID 0)
-- Dependencies: 223
-- Name: registration_registration_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.registration_registration_id_seq OWNED BY public.registration.registration_id;


--
-- TOC entry 222 (class 1259 OID 24832)
-- Name: student_schedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_schedule (
    student_schedule_id integer NOT NULL,
    sex character varying(10),
    dept character varying(20),
    validated character varying(10),
    code character varying(255),
    subject character varying(255),
    description character varying(255),
    units double precision,
    schedule character varying(255),
    instructor character varying(255),
    section character varying(255),
    id integer NOT NULL
);


ALTER TABLE public.student_schedule OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 24909)
-- Name: student_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 24831)
-- Name: student_schedule_student_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.student_schedule_student_schedule_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.student_schedule_student_schedule_id_seq OWNER TO postgres;

--
-- TOC entry 5050 (class 0 OID 0)
-- Dependencies: 221
-- Name: student_schedule_student_schedule_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.student_schedule_student_schedule_id_seq OWNED BY public.student_schedule.student_schedule_id;


--
-- TOC entry 226 (class 1259 OID 24883)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 24882)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4873 (class 2604 OID 24889)
-- Name: admission student_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admission ALTER COLUMN student_id SET DEFAULT nextval('public.admission_student_id_seq'::regclass);


--
-- TOC entry 4875 (class 2604 OID 24864)
-- Name: registration registration_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registration ALTER COLUMN registration_id SET DEFAULT nextval('public.registration_registration_id_seq'::regclass);


--
-- TOC entry 4874 (class 2604 OID 24835)
-- Name: student_schedule student_schedule_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_schedule ALTER COLUMN student_schedule_id SET DEFAULT nextval('public.student_schedule_student_schedule_id_seq'::regclass);


--
-- TOC entry 5034 (class 0 OID 24800)
-- Dependencies: 220
-- Data for Name: admission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admission (student_id, first_name, last_name, program, year_level, sex, section, department, validated, id) FROM stdin;
5	Krisha Mae	Dador	BSIT	2	F	BSIT2A	CEC	t	1
6	Princess Karyll	Chavez	BSIT	2	F	BSIT2A	CEC	t	2
7	Princess Karyll	Chavez	BSIT	2	M	BSIT2A	CEC	t	3
8	Jepoy	Dizon	BSIT	2	M	BSIT2C	CEC	t	4
\.


--
-- TOC entry 5038 (class 0 OID 24861)
-- Dependencies: 224
-- Data for Name: registration; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.registration (registration_id, student_id, student_schedule_id, status, date_enrolled) FROM stdin;
\.


--
-- TOC entry 5036 (class 0 OID 24832)
-- Dependencies: 222
-- Data for Name: student_schedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.student_schedule (student_schedule_id, sex, dept, validated, code, subject, description, units, schedule, instructor, section, id) FROM stdin;
2	F	CEC	Yes	 CC5	 CC5	Information Management	3	3-5pm T ITRM3	F.Penalosa	BSIT2A	2
3	\N	\N	\N	Web Dev	Web Dev	Information Management	3	3-5pm	F.Penalosa	BSIT2A	3
4	\N	\N	\N	C677	CC5	Data Management	3	3-5pm T ITRM3	F.Penalosa	BSIT2A	4
5	\N	\N	\N	CS101	Computer Programming 1	Introduction to programming using C++	3	MWF 9:00-10:30 AM	Dr. Santos	BSIT-1A	5
6	\N	\N	\N	CS102	Discrete Mathematics	Logic, sets, relations, and functions	3	TTH 10:30-12:00 PM	Prof. Reyes	BSIT-1A	6
7	\N	\N	\N	IT201	Data Structures	Stacks, queues, linked lists, trees	3	MWF 1:00-2:30 PM	Engr. Dela Cruz	BSIT-2A	7
8	\N	\N	\N	IT202	Object-Oriented Programming	Classes, objects, inheritance, polymorphism	3	TTH 2:30-4:00 PM	Dr. Garcia	BSIT-2A	8
9	\N	\N	\N	IT203	Database Systems	Relational databases and SQL fundamentals	3	MWF 3:00-4:30 PM	Prof. Lim	BSIT-2B	9
10	\N	\N	\N	GE101	Purposive Communication	Effective communication in academic and professional settings	3	TTH 8:00-9:30 AM	Ms. Navarro	BSIT-1B	10
\.


--
-- TOC entry 5040 (class 0 OID 24883)
-- Dependencies: 226
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, name) FROM stdin;
\.


--
-- TOC entry 5051 (class 0 OID 0)
-- Dependencies: 228
-- Name: admission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admission_id_seq', 4, true);


--
-- TOC entry 5052 (class 0 OID 0)
-- Dependencies: 219
-- Name: admission_student_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admission_student_id_seq', 8, true);


--
-- TOC entry 5053 (class 0 OID 0)
-- Dependencies: 223
-- Name: registration_registration_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.registration_registration_id_seq', 1, false);


--
-- TOC entry 5054 (class 0 OID 0)
-- Dependencies: 227
-- Name: student_schedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.student_schedule_id_seq', 10, true);


--
-- TOC entry 5055 (class 0 OID 0)
-- Dependencies: 221
-- Name: student_schedule_student_schedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.student_schedule_student_schedule_id_seq', 10, true);


--
-- TOC entry 5056 (class 0 OID 0)
-- Dependencies: 225
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- TOC entry 4877 (class 2606 OID 24891)
-- Name: admission admission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admission
    ADD CONSTRAINT admission_pkey PRIMARY KEY (student_id);


--
-- TOC entry 4881 (class 2606 OID 24867)
-- Name: registration registration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registration
    ADD CONSTRAINT registration_pkey PRIMARY KEY (registration_id);


--
-- TOC entry 4879 (class 2606 OID 24838)
-- Name: student_schedule student_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_schedule
    ADD CONSTRAINT student_schedule_pkey PRIMARY KEY (student_schedule_id);


--
-- TOC entry 4883 (class 2606 OID 24888)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4884 (class 2606 OID 24898)
-- Name: registration registration_student_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registration
    ADD CONSTRAINT registration_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.admission(student_id);


--
-- TOC entry 4885 (class 2606 OID 24873)
-- Name: registration registration_student_schedule_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registration
    ADD CONSTRAINT registration_student_schedule_id_fkey FOREIGN KEY (student_schedule_id) REFERENCES public.student_schedule(student_schedule_id);


-- Completed on 2026-05-04 19:12:30

--
-- PostgreSQL database dump complete
--

\unrestrict NhRcb8A1qdsE1pwK5yqCE4kaUx1pWKFM7UJRDq1raEwz9EZNPX9Xo4dFJOrPCfJ

